hunspell.lo: /home/src/php-hunspell/hunspell.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/src/php-hunspell $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/src/php-hunspell/hunspell.c -o hunspell.lo 
$(phplibdir)/hunspell.la: ./hunspell.la
	$(LIBTOOL) --mode=install cp ./hunspell.la $(phplibdir)

./hunspell.la: $(shared_objects_hunspell) $(HUNSPELL_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_hunspell) $(HUNSPELL_SHARED_LIBADD)

